project:
  type: website
  render: 
    - "*.qmd"

execute: 
  freeze: auto
  
website:
  title: "UP 591: Capstone Seminar"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: syllabus/syllabus.qmd
        text: "Syllabus"
      - href: milestones/milestones.qmd
        text: "Milestones"
      - href: schedule/schedule.qmd
        text: "Schedule"
    search: true
  favicon: favicon.png
  page-footer:
    left: "Content {{< fa regular copyright >}} Andrew J. Greenlee"
    right: "Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/) </br> Website Code on [Github {{< fa brands github >}}]({{< var course.github >}})"

  sidebar:
    - title: "Schedule"
      style: "docked"
      contents:
        - section: "Schedule"
          contents:
            - text: "Schedule Overview"
              file: schedule/schedule.qmd
            - text: "Week 1: Welcome and Introduction"
              file: schedule/01_introduction.qmd
    - title: "Milestones"
      style: "docked"
      contents:
        - section: "Milestones Overview"
          contents:
            - text: "Plan of Study Update"
              file: schedule/01_planofstudy.qmd
            - text: "Capstone Adoption"
              file: schedule/02_capstoneadoption.qmd
            - text: "Monthly Progress Memo"
              file: schedule/03_progressmemo.qmd
            - text: "Professional Development Plan"
              file: schedule/04_developmentplan.qmd
            - text: "Portfolio"
              file: schedule/05_portfolio.qmd
            - text: "Capstone"
              file: schedule/06_capstone.qmd
format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: darkly
    css: 
      - styles.css
    toc: true

editor: source

